<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Nikse.SubtitleEdit.Tests.SmokeTest</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="CertificationTest.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ui\UI.csproj" />
  </ItemGroup>

</Project>